"""The Kaggle kernel body is generated by string substitution and then run
unattended on a GPU we're paying for in quota, so a typo in the template is
expensive to discover. Check it renders to valid Python with the right knobs."""
import importlib.util
import json
import py_compile
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

_spec = importlib.util.spec_from_file_location("kaggle_run", REPO_ROOT / "scripts" / "kaggle_run.py")
kaggle_run = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(kaggle_run)


class TestKagglePayload(unittest.TestCase):
    def _build(self, stage="smoke", tmp=None):
        work_dir = Path(tmp)
        kaggle_run.build_payload(stage, "https://github.com/o/r.git", "main", "user/slug", work_dir)
        return (
            (work_dir / "run_pilot.py").read_text(),
            json.loads((work_dir / "kernel-metadata.json").read_text()),
            work_dir,
        )

    def test_renders_valid_python_with_no_placeholders_left(self):
        with tempfile.TemporaryDirectory() as tmp:
            body, _, work_dir = self._build(tmp=tmp)
            py_compile.compile(str(work_dir / "run_pilot.py"), doraise=True)
            for placeholder in ("__REPO_URL__", "__BRANCH__", "__STAGE__"):
                self.assertNotIn(placeholder, body)

    def test_substitutes_stage_repo_and_branch(self):
        with tempfile.TemporaryDirectory() as tmp:
            body, _, _ = self._build(stage="sweep", tmp=tmp)
            self.assertIn('STAGE = "sweep"', body)
            self.assertIn('REPO_URL = "https://github.com/o/r.git"', body)
            self.assertIn('BRANCH = "main"', body)

    def test_metadata_pins_a_t4_not_a_p100(self):
        # A P100 is sm_60 and Kaggle's own preinstalled torch only ships
        # sm_70+ kernels, so letting Kaggle pick the accelerator (the
        # deprecated enable_gpu path) fails every CUDA call at runtime.
        with tempfile.TemporaryDirectory() as tmp:
            _, meta, _ = self._build(tmp=tmp)
            self.assertEqual(meta["machine_shape"], "NvidiaTeslaT4")

    def test_title_matches_the_id_slug(self):
        # Kaggle slugs from the title, not the id, and silently creates a
        # different kernel when they disagree.
        with tempfile.TemporaryDirectory() as tmp:
            _, meta, _ = self._build(tmp=tmp)
            self.assertEqual(meta["title"], meta["id"].split("/", 1)[1])

    def test_metadata_requests_gpu_and_internet(self):
        with tempfile.TemporaryDirectory() as tmp:
            _, meta, _ = self._build(tmp=tmp)
            self.assertTrue(meta["enable_gpu"])
            self.assertTrue(meta["enable_internet"])
            self.assertEqual(meta["id"], "user/slug")
            self.assertEqual(meta["code_file"], "run_pilot.py")
            self.assertEqual(meta["kernel_type"], "script")

    def test_every_cli_stage_is_handled_by_the_template(self):
        # The template raises on an unknown stage; make sure the CLI's choices
        # and the template's STAGES table can't drift apart silently.
        template = (REPO_ROOT / "kaggle" / "run_pilot_template.py").read_text()
        for stage in ("smoke", "poscontrol", "ratio", "format", "contrastive", "fictional",
                      "biography", "instruct", "replicate10", "survey", "displace05", "displace15", "promptbase", "displacephi3", "baseline", "sweep", "all"):
            self.assertIn(f'"{stage}":', template)


if __name__ == "__main__":
    unittest.main()
